version: '3'

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_DATABASE_URL=jdbc:postgresql://db:5432/nifi
      - NIFI_DATABASE_DRIVER=org.postgresql.Driver
      - NIFI_DATABASE_USERNAME=nifi
      - NIFI_DATABASE_PASSWORD=nifi
    depends_on:
      - db
      - pgadmin
    networks:
      - my-network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nifi
      - POSTGRES_PASSWORD=nifi
      - POSTGRES_DB=nifi
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data:
  pgadmin-data:
